title: "Adeel Farooq"
email: your.email@domain.com
description: >-
  Postdoctoral Researcher in Microbial Genomics, AMR, and Bioinformatics.
baseurl: ""
url: "https://adeeffarooq.github.io"
theme: minimal-mistakes-jekyll

author:
  name   : "Adeel Farooq"
  avatar : "/assets/images/profile.jpg"
  bio    : "Postdoc | Microbial Genomics | AMR | Fermentation Bioinformatics"
  location: "Guelph, Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/AdeefFarooq"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
